routes/web.php
<?php
 
use App\User;

/*===========================
=            WEB            =
===========================*/



Auth::routes(['verify'=>true]);


Route::get('usuarios','WebController@usuarios');
Route::get('test/','WebController@test');
Route::get('chart','WebController@chart');

Route::get('/visitante/citas','WebController@citas');
Route::get('/visitante/especialidades','WebController@especialidades');

Route::get('/visitante/especialidad/{id}','WebController@especialidad');

Route::get('/visitante/consultorios','WebController@consultorios');
Route::get('/visitante/consultorio/{id}','WebController@consultorio');
Route::get('/visitante/mapa/{id}','WebController@mapa');

Route::get('/visitante/doctor/{id}','WebController@doctor');
Route::get('/visitante/doctores/','WebController@doctores');
Route::get('/visitante/','WebController@visitante');


Route::get('acerca','WebController@acerca');
Route::get('contacto','WebController@contacto');


Route::post('/contacto','WebController@contactus')->name('contact.us');

/*=====  End of WEB  ======*/




Route::group(['middleware' => ['auth','admin'] ], function () {
    route::get('admin/create','AdminController@create')->name('admin.create');
});


/*====================================
=            AUTH PATIENT            =
====================================*/


Route::group(['middleware' => ['auth','patient'] ], function () {

    Route::get('payment','PaymentController@index')->name('payment.index');
    Route::get('payment/create','PaymentController@create')->name('payment.create');
    Route::get('payment/billingPortal','PaymentController@billingPortal')->name('billingPortal');
    Route::post('payment','PaymentController@store')->name('payment.store');
    Route::post('payment/other','PaymentController@other')->name('payment.store.other');
    Route::get('invoice/download/{payment}','InvoiceController@download')->name('invoice.download');
 
     Route::post('pay/{appointment}/online','PaymentController@online')->name('payment.store.online');
    Route::post('pay/{appointment}/invoice','PaymentController@invoice')->name('payment.store.invoice');


    Route::post('pay/{appointment}/then','PaymentController@then')->name('payment.then');
    Route::get('payment/{appointment}/doctor','PaymentController@doctor')->name('payment.doctor');
 
    Route::get('payment/{appointment}/user','PaymentController@user')->name('payment.user');
    //

    Route::get('chatbot','ChatController@bot')->name('chatbot');
    Route::resource('appointment', 'AppointmentController');          
  
    Route::post('appointment/create/{doctor}','AppointmentController@createWithDoctor');


    Route::get('appointment/create/{id_doctor}/{id_speciality}','AppointmentController@create');

    Route::get('appointment/create','AppointmentController@create');
    Route::get('doctor', 'DoctorController@index');
    Route::get('office', 'OfficeController@index');
    

    Route::get('speciality','SpecialityController@index');

    Route::get('prescription/download/{id}', 'PrescriptionController@download');

///


    Route::get('notifications/','NotificationController@index')->name('notifications.index');




    //review

    Route::put('review/{appointment}', 'ReviewController@store')->name('review.store');


});
/*=====  End of AUTH PATIENT  ======*/

/*====================================
=            AUTH doctor            =
====================================*/


Route::group(['middleware' => ['auth','doctor'] ], function () {

    Route::get('patient','PatientController@index');

    Route::patch('doctor/edit/{doctor}', 'DoctorController@edit');

    Route::get('doctor/{id}/edit', 'DoctorController@edit');
    Route::post('prescription/store','PrescriptionController@store');
    Route::post('prescription/update','PrescriptionController@update');
    Route::get('prescription','PrescriptionController@index');
    Route::get('prescription/download/{id}', 'PrescriptionController@download');



    /*----------  char  ----------*/
    




route::get('profile/image/{id}','ProfileController@image')->name('profile.image');
    

    route::get('chat','chatController@index');
    // route::post('chat/count/','chatController@count');
    // route::post('chat/total/','chatController@total');




    // admin


    route::get('admin/{admin}','AdminController@show')->name('admin.show');


});
/*=====  End of AUTH doctor  ======*/

/*====================================
=            AUTH office            =
====================================*/


Route::group(['middleware' => ['auth','office'] ], function () {


route::put('profile/regenerate/{user}','ProfileController@regenerate')->name('profile.regenerate');


    Route::delete('patient/{patient}/destroy','PatientController@destroy');
    Route::get('patient/create','PatientController@create');
    Route::post('patient/store','PatientController@store')->name('patient.store');
    Route::delete('doctor/destroy/{doctor}', 'DoctorController@destroy');


//    Route::get('office/{id}/edit','OfficeController@edit');
    Route::patch('office','OfficeController@update');


    Route::get('doctor/create', 'DoctorController@create')->name('doctor.create');
    Route::post('doctor/store', 'DoctorController@store')->name('doctor.store');


    /*----------  especialidades  ----------*/


    route::post('speciality/store','SpecialityController@store');
    route::post('speciality/update','SpecialityController@update');

    route::delete('speciality/store','SpecialityController@destroy');
    /*----------  users  ----------*/

    route::get('user','UserController@index');



});
/*=====  End of AUTH office  ======*/


/*==================================
=            auth ADMIN            =
==================================*/



/*=====  End of auth ADMIN  ======*/

Route::group(['middleware' => ['auth','admin'] ], function () {





    /*----------  Facturas  ----------*/


    route::get('bills','BillController@index');
 
    /*----------  opciones  ----------*/



    route::get('options','optionController@index');
    route::post('options/user-default','optionController@userDefault');
    route::post('options/moneda','optionController@moneda');
    route::post('options/idioma','optionController@idioma');




    /*----------  Office  ----------*/

    route::get('office/create','OfficeController@create');
    route::post('office/store','OfficeController@store')->name('office.store');
    route::delete('office/{office}/delete','OfficeController@destroy');


    


// admin


    route::get('admin/{admin}/edit','AdminController@edit')->name('admin.edit');
    route::post('admin','AdminController@store')->name('admin.store');
    route::put('admin/{admin}','AdminController@update')->name('admin.update');
     Route::put('admin/{admin}/login', 'AdminController@updateLogin')->name('admin.update.login');
     Route::put('admin/{admin}/image', 'AdminController@updateImage')->name('admin.update.image');
     
    // user

     Route::put('user/{user}/block', 'UserController@block')->name('user.block');

});



/*============================
=            AUTH            =
============================*/


Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::patch('appointment/attend/{appointment}', 'AppointmentController@attend');
    Route::patch('appointment/rejected/{appointment}', 'AppointmentController@rejected');
    Route::patch('appointment/accepted/{appointment}', 'AppointmentController@accepted');
    Route::patch('appointment/cancelled/{appointment}', 'AppointmentController@cancelled');

    Route::patch('appointment/pending/{appointment}', 'AppointmentController@pending');
    Route::patch('appointment/late/{appointment}', 'AppointmentController@late');
    Route::patch('appointment/lost/{appointment}', 'AppointmentController@lost');


    ///////////////////// prscriptions

    Route::get('prescription','PrescriptionController@index');




//api


    Route::post('api/appointment/gettime','API\\ApiController@AppointmentGetTime');

    /*----------  comments  ----------*/
    
    Route::post('/appointment/comment/register','Appointment_commentController@register');
    Route::post('/appointment/comment/delete','Appointment_commentController@destroy');
    Route::post('/appointment/comment/update','Appointment_commentController@update');


});




/*=====  End of AUTH  ======*/
///////////////////////////////////////////////////////////////////////////////////////////////////   


Route::group(['middleware' => ['auth','patient'] ], function () {

   Route::get('like','LikeController@index')->name('like.index');


   Route::get('wizard','HomeController@wizard')->name('wizard');


   Route::get('patient/{id}','PatientController@show');
   Route::get('patient/{id}/edit','PatientController@edit');
   Route::put('patient/{patient}','PatientController@update')->name('patient.update');


   Route::get('office/{id}' ,'OfficeController@show')->name('office.show');
   Route::get('doctor/{id}','DoctorController@show')->name('doctor.show');


   route::get('speciality/{id}','SpecialityController@show');



   Route::put('profile/{user}/login','ProfileController@updateLogin')->name('profile.update.login');
   Route::put('profile/{user}/image','ProfileController@updateImage')->name('profile.update.image');


});

Route::group(['middleware' => ['auth','doctor'] ], function () {

     Route::put('doctor/{doctor}', 'DoctorController@update')->name('doctor.update');
     Route::put('doctor/{id}/login', 'DoctorController@updateLogin')->name('doctor.update.login');
     Route::put('doctor/{id}/image', 'DoctorController@updateImage')->name('doctor.update.image');
     

});


Route::group(['middleware' => ['auth','office'] ], function () {



    Route::get('office/{id}/edit','OfficeController@edit');

     Route::put('office/{office}', 'OfficeController@update')->name('office.update');

app/Speciality.php
<?php

namespace App;

use App\Doctor;
use App\Options;
use App\Soft\Levenshtein;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Speciality extends Model
{

    use SoftDeletes;

    public function doctor_speciality()
    {
        return $this->hasMany('App\Doctor_speciality');
    }

    public function getdoctorsAttribute(){

        return Doctor::join('doctor_specialities','doctors.id','doctor_specialities.doctor_id')
        ->select('doctors.*')
        ->where('doctor_specialities.speciality_id',$this->id)
        ->get();


    }
    public function getpriceAttribute()
    {
        return  strtoupper(config('cashier.currency')) . "$ ". $this->cost;
    }

    public function getcostAttribute(){

        $min=999999;
        foreach($this->doctor_speciality as $de){
            if($de->cost < $min)
                $min=$de->cost;
        }

        return $min ==  999999 ? 0 : $min;
    }

    public function getstarsAttribute()
    {

        $contador = 0;
        $sumatoria = 0;
        foreach ($this->doctor_speciality as $relation) {
            $doctor = $relation->doctor;
            if ($doctor->stars > 0) {

                $contador++;
                $sumatoria += $doctor->stars;
            }
        }

        if ($contador == 0) {
            return "No hay calificaciones";
        }



        return round($sumatoria / $contador, 1);
    }


    public function getStarsEarnedAttribute()
    {
        return round($this->stars);
    }

    public function getStarsMissingAttribute()
    {
        return 5 - $this->StarsEarned;
        
    }


    public static function search($s )
    {
       
        $specialities = Speciality::all();
        


        return Levenshtein::searchIn($specialities, $s);
    }
    

}

app/Http/Controllers/SpecialityController.php
<?php

namespace App\Http\Controllers;

use App\Speciality;
use Illuminate\Http\Request;
use  Illuminate\Support\Facades\Auth;

class SpecialityController extends Controller
{
    public function index()
    {

        if (Auth::user()->Patient()) {


            $specialities = Speciality::All();

            return view('hospital.Speciality.indexSpeciality', compact('specialities'));
        }

        return view('admin');
    }

    public function store(Request $request)
    {
      $data = request()->validate([
        'name' => 'required|string|max:255',
       
        

    ]);
      $especialidad = new Speciality();

      $especialidad->name = $data['name'];
    

      $especialidad->save();


      return back()->with('success', '¡Especialidad Agregada con Exito!');
  }

  public function show($id)
  {

    $speciality = Speciality::find($id);



    return view('hospital.Speciality.showSpeciality', compact('speciality'))->with('doctors', $speciality->doctors);
}

public function update(Request $request)
{
      $data = request()->validate([
        'name' => 'required|string|max:255',
       
        

    ]);
  $especialidad = Speciality::find($request->input('id'));
      $especialidad->name = $data['name'];
      

  $especialidad->save();


  return back()->with('success', '¡Especialidad Actualizada con Exito!');
}


public function destroy(Request $request)
{

    $especialidad = Speciality::find($request->input('id'));



    $especialidad->delete();

    return back()->with('success', '¡Especialidad eliminada con Exito!');
}
}

resources/views/hospital/Speciality/indexSpeciality.blade.php
@extends ('layouts.nav-admin')

@section('content')

@if(Auth::user()->Office())

<button class="btn btn-success  btn-float" data-toggle="modal" data-target="#AgregarEspecialidad">
  <i class="fal fa-plus"></i>
</button>

<!-- Modal Crear -->
<div class="modal fade" id="AgregarEspecialidad" tabindex="-1" role="dialog" aria-labelledby="AgregarEspecialidadLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="AgregarEspecialidadLabel"><i class="fal fa-plus"></i> Agregar Especialidad</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {!! Form::open(['action' => 'SpecialityController@store', 'method' => 'POST']) !!}
      <div class="modal-body">
        {{ csrf_field()}}

        <div class="form-group form-inline align-items-end">

          <div class="icon-form">
            <i class="fal fa-file-certificate"></i>
          </div>
          <div class="form-group">

            {{Form::text('name', '', ['class'=>'form-control','placeholder'=>'Nombre especialidad'])}}


          </div>
        </div>
        

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <button type="submit" class="btn btn-primary"><i class="fal fa-save"></i> Guardar</button>
      </div>
      {!! Form::close() !!}

    </div>
  </div>
</div>



<!-- Modal Actializar -->



<div class="modal fade" id="ActualizarEspecialidad" tabindex="-1" role="dialog" aria-labelledby="ActualizarEspecialidadLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="ActualizarEspecialidadLabel"><i class="fal fa-plus"></i>Actualizar especialidad</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {!! Form::open(['action' => 'SpecialityController@update','class'=>'actualizar-especialidad', 'method' => 'POST']) !!}
      <div class="modal-body">
        {{ csrf_field()}}

        <div class="form-group form-inline align-items-end">

          <div class="icon-form">
            <i class="fal fa-file-certificate"></i>
          </div>
          <div class="form-group">


            {{Form::hidden('id')}}

            {{Form::text('name', '', ['class'=>'form-control','placeholder'=>'Nuevo Nombre'])}}


          </div>
        </div>
        


      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <button type="submit" class="btn btn-primary"><i class="fal fa-save"></i> Guardar</button>
      </div>
      {!! Form::close() !!}

    </div>
  </div>
</div>

@endif

@if(count($specialities) < 1) <div class="container p-5 sin-datos">
  <div class="row">
    <div class="col text-center">
      <i class="fal fa-user-md"></i>
      <p class="lead ">No se encontraron especialidades.

        @if(Auth::user()->Office())<a href="{{ url('/speciality/create')}}">¡Agrega uno!</a></p>@endif
    </div>
  </div>
  </div>



  @else
  <div class="container">

    <div class="row">
      <div class="col-12 d-none d-md-block">
        <div class="card">
          <div class="card-encabezado">

            <div class="card-cabecera-icono bg-info sombra-2 ">

              <i class="fal fa-list"></i>
            </div>
            <div class="card-title">Listado de especialidades</div>
          </div>

          <div class="card-body table-responsives">

            <table class="table" id="data_table">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Nombre</th>
                  <th>Estrellas</th>
                  <th>Precio</th>
                  <th>Cantidad de doctores</th>
                  <th>Acciones</th>

                </tr>
              </thead>
              <tbody>
                @foreach ($specialities as $speciality)
                <tr>
                  <td>{{$speciality->id}}</td>
                  <td>{{ $speciality->name }}</td>
                  <td>{{ $speciality->stars }}</td>

                  <td>{{ $speciality->price }}</td>
                  <td>{{$speciality->doctor_speciality->count()}}</td>


                  <td><a href="{{url('/speciality/'.$speciality->id)}}" class="btn btn-primary btn-round btn-just-icon btn-sm"><i class="fal fa-file-certificate"></i></a>



                    @if(Auth::user()->Office())

                    <button type="button" class="btn btn-success btn-round btn-just-icon btn-sm btn-actualizar-especialidad" data-id="{{$speciality->id}}" data-cost="{{$speciality->cost}}" data-name="{{$speciality->name}}" data-toggle="modal" data-target="#ActualizarEspecialidad"><i class="fal fa-pen"></i></button>

                    @if (count($speciality->doctor_speciality)<1) <button class="btn btn-danger btn-round btn-just-icon btn-sm btn-confirm-delete" id='speciality-{{$speciality->id}}'> <i class="fas fa-times"></i></button>



                      {!! Form::open(['action' => ['SpecialityController@destroy'], 'method' => 'POST']) !!}

                      <input type="hidden" name="id" value="{{$speciality->id}}">
                      {{csrf_field()}}

                      {{ method_field('DELETE')}}




                      {{ Form::submit('Eliminar', ['class' => 'btn-delete d-none', 'id'=>'speciality-'.$speciality->id]) }}
                      {!! Form::close() !!}
                      @endif


                  </td>
                  @endif

                </tr>
                @endforeach

              </tbody>
            </table>

          </div>
        </div>

      </div>


      <div class="col-12 d-block d-md-none">





        @foreach ($specialities as $speciality)
        <div class="card   my-5">
          <div class="card-encabezado">

            <div class="card-cabecera-icono bg-info sombra-2 ">

              <i class="fal fa-file-certificate"></i>
            </div>
            <div class="card-title">{{$speciality->name}}</div>
          </div>

          <div class="card-body">


            <div class="form-inline mb-2">
              <div class="icon-form">
                <i class="fas fa-user-md"></i>
              </div>

              <div class="icon-texto">

                <span class="color-principal">Cantidad de medicos </span> {{count($speciality->doctor_speciality)}}
              </div>

            </div>
            <div class="form-inline mb-2">
              <div class="icon-form">
                <i class="fas fa-user-md"></i>
              </div>

              <div class="icon-texto">

                <span class="color-principal">Precio </span> {{$speciality->price}}
              </div>

            </div>
            <div class="text-center">
              <a href="{{url('/speciality/'.$speciality->id)}}" class="btn btn-primary btn-round btn-just-icon btn-sm"><i class="fal fa-file-certificate"></i></a>



              @if(Auth::user()->Office())
              <button type="button" class="btn btn-success btn-round btn-just-icon btn-sm btn-actualizar-especialidad" data-id="{{$speciality->id}}" data-name="{{$speciality->name}}" data-toggle="modal" data-target="#ActualizarEspecialidad"><i class="fal fa-pen"></i></button>

              @if (count($speciality->doctor_speciality)<1) <button class="btn btn-danger btn-round btn-just-icon btn-sm btn-confirm-delete" id='speciality-{{$speciality->id}}'> <i class="fas fa-times"></i></button>



                {!! Form::open(['action' => ['SpecialityController@destroy'], 'method' => 'POST']) !!}

                <input type="hidden" name="id" value="{{$speciality->id}}">
                {{csrf_field()}}

                {{ method_field('DELETE')}}




                {{ Form::submit('Eliminar', ['class' => 'btn-delete d-none', 'id'=>'speciality-'.$speciality->id]) }}
                {!! Form::close() !!}
                @endif


                </td>
                @endif


            </div>
          </div>

        </div>

        @endforeach


      </div>



    </div>
  </div>

  @endif
  @endsection
  

resources/views/hospital/Speciality/showSpeciality.blade.php
@extends ('layouts.nav-admin')

@section('content')


<!-- Modal Actializar -->



@include('hospital.includes.tableDoctor')

@endsection
@include('includes.dataTables')